---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-metrics-server-ingress
  namespace: kube-system
  annotations:
    #configmanagement.gke.io/cluster-selector: ${CLUSTER_SELECTOR}
spec:
  podSelector: 
    matchLabels:
      k8s-app: metrics-server
  policyTypes:
  - Ingress
  ingress:
  - from:
     - ipBlock:
        cidr: ${APISERVER_IP}/32
     - ipBlock:
        cidr: ${NODE_CIDR}
    ports:
    - protocol: TCP
      port: 443
